name: block_push
args: []
kwargs: {}

dataset:
  _target_: "datasets.block_push_dset.load_block_push_slice_train_val"
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/block_pushing_combined
  split_ratio: 0.9
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 16