name: deformable_env_SOLV
args: []
kwargs: 
  object_name: "granular"

load_dir: ""

dataset:
  _target_: "datasets.deformable_env_dset.load_deformable_dset_slice_train_val"
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/deformable
  object_name: ${object_name}
  split_ratio: 0.9
  transform:
    _target_: "datasets.img_transforms.imagenet_transform"
    img_size: ${img_size}
  object: ${object}
  encoder: 'dino_small'
  num_clusters: ${num_clusters}
  folder_name: 'ft'

decoder_path: null
num_workers: 16
