name: point_maze
args: []
kwargs: {}

dataset:
  _target_: "datasets.point_maze_dset.load_point_maze_slice_train_val"
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/point_maze
  split_ratio: 0.9
  transform:
    _target_: "datasets.img_transforms.imagenet_transform"
    img_size: ${img_size}
  encoder: 'dino_small'
  object: ${object}
  num_clusters: ${num_clusters}
  num_features: ${num_features}
  use_coord: ${use_coord}
  use_patch_info: ${use_patch_info}

decoder_path: null
num_workers: 16