name: pusht_object
args: []
kwargs: 
  with_velocity: true
  with_target: true

dataset:
  _target_: "datasets.pusht_dset.load_pusht_slice_train_val"
  with_velocity: true
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/pusht_noise
  split_ratio: 0.9
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}
  encoder: 'dino_small'
  object: ${object}
  num_clusters: ${num_clusters}
  num_features: ${num_features}
  use_coord: ${use_coord}
  use_patch_info: ${use_patch_info}

decoder_path: null
num_workers: 10